TooN: Linear equation solvers
Linear equation solvers
Classes to solve linear equations.
Classes
struct RobustI< Precision >
Robust reweighting (type I) for IRLS.
struct RobustII< Precision >
Robust reweighting (type II) for IRLS.
struct ILinear< Precision >
A reweighting class representing no reweighting in IRLS.
struct RobustIII< Precision >
A reweighting class where the objective function tends to a fixed value, rather than infinity.
class IRLS< Size, Precision, Reweight >
Performs iterative reweighted least squares.
class WLS< Size, Precision, Decomposition >
Performs Gauss-Newton weighted least squares computation.
Functions
template<int N, typename Precision >
Vector< N, Precision > gaussian_elimination (Matrix< N, N, Precision > A, Vector< N, Precision > b)
template<int R1, int C1, int R2, int C2, typename Precision >
Matrix< Internal::Size3< R1,
C1, R2 >::s, C2, Precision > gaussian_elimination (Matrix< R1, C1, Precision > A, Matrix< R2, C2, Precision > b)
Detailed Description
Classes to solve linear equations.
Function Documentation
Vector<N, Precision> TooN::gaussian_elimination (Matrix< N, N, Precision > A, Vector< N, Precision > b)
Return the solution for , given and .
Parameters:
A
b
References Vector< Size, Precision, Base >::size().
Referenced by TooN::sqrt().
Matrix<Internal::Size3<R1, C1, R2>::s, C2, Precision> TooN::gaussian_elimination (Matrix< R1, C1, Precision > A, Matrix< R2, C2, Precision > b)
Return the solution for , given and .
Parameters:
A
b
References Matrix< Rows, Cols, Precision, Layout >::num_cols(), and Matrix< Rows, Cols, Precision, Layout >::num_rows().